version: "3.9"

services:
  ros2_humble:
    image: osrf/ros:humble-desktop-full
    container_name: ros2_humble
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev
      - ~/Echo:/root/Echo
    working_dir: /root/Echo
    stdin_open: true   # -it (interactive)
    tty: true          # -it (tty)
